INSERT INTO 'applicants' 
('student_id', 'last_name', 'other_names', 'gender', 'marital_status','nationality', 'province', 'address', 'email', 'year_of_study', 
	'program_of_study', 'program_duration', 'school', 'sponsorship', 'medical_condition', 'score', 'allocated') 
VALUES
('Zulu', 'Mary', '00-00-0000', 'Zambian', 'Female', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 14060000, 'Fourth', 'Biology', 'Four','GRZ 100%', 'Humanities','No', 0,'N'),
('Mumba', 'Mercy', '00-00-0000', 'Zambian', 'Female', 'Single', 'Ngombe compound', 'Luapula', 'email@mail.com', 14050036, 'Fourth', 'Biology', 'Five','GRZ 75%', 'Humanities ','No', 0,'N'),
('Mwansa', 'Maria', '00-00-0000', 'Zambian', 'Female', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 14051116, 'Fourth', 'Biology', 'Four','GRZ 100%', 'Natural Sciences','Yes', 0,'N'),
('Phiri', 'Stella', '00-00-0000', 'Zambian', 'Female', 'Single', 'Ngombe compound', 'Western', 'email@mail.com', 14836236, 'Fourth', 'Biology', 'Five','GRZ 75%', 'Humanities ','No', 0,'N'),
('Chileshe', 'Cecilia', '00-00-0000', 'Zambian', 'Female', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 14053216, 'Fourth', 'Biology', 'Four','GRZ 100%', 'Natural Sciences','Yes', 0,'N'),
('Mutale', 'Precious', '00-00-0000', 'Zambian', 'Female', 'Single', 'Ngombe compound', 'Eastern', 'email@mail.com', 14021236, 'Fourth', 'Biology', 'Four','GRZ 75%', 'Humanities ','No', 0,'N'),
('Zulu', 'Jane', '00-00-0000', 'Zambian', 'Female', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 13953536, 'Fourth', 'Biology', 'Four','GRZ 75%', 'Natural Sciences','No', 0,'N'),
('Mumba', 'Florence', '00-00-0000', 'Zambian', 'Female', 'Single', 'Ngombe compound', 'Luapula', 'email@mail.com', 12053536, 'Fourth', 'Biology', 'Five','GRZ 100%', 'Education ','No', 0,'N'),
('Mwewa', 'Salome', '00-00-0000', 'Zambian', 'Female', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 11053536, 'Fourth', 'Biology', 'Four','GRZ 75%', 'Humanities ','No', 0,'N'),
('Lungu', 'Santana', '00-00-0000', 'Zambian', 'Female', 'Single', 'Ngombe compound', 'Muchinga', 'email@mail.com', 14059876, 'Fourth', 'Biology', 'Four','GRZ 75%', 'Natural Sciences','No', 0,'N'),
('Hamoba', 'Gedaida', '00-00-0000', 'Zambian', 'Female', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 14055287, 'Fourth', 'Biology', 'Five','GRZ 100%', 'Natural Sciences','No', 0,'N'),
('Mulundu', 'Mary', '00-00-0000', 'Zambian', 'Female', 'Single', 'Ngombe compound', 'Copperbelt', 'email@mail.com', 14098206, 'Fourth', 'Biology', 'Four','GRZ 75%', 'Humanities','No', 0,'N'),
('Silanda', 'Sibo', '00-00-0000', 'Zambian', 'Female', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 14054566, 'Fourth', 'Biology', 'Four','GRZ 100%', 'Humanities','No', 0,'N'),
('Zulu', 'Orlando', '00-00-0000', 'Zambian', 'Female', 'Single', 'Ngombe compound', 'Northern', 'email@mail.com', 14053326, 'Fourth', 'Biology', 'Five','GRZ 75%', 'Education','No', 0,'N'),
('Fwaka', 'Miriam', '00-00-0000', 'Zambian', 'Female', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 16053536, 'Fourth', 'Biology', 'Four','GRZ 100%', 'Natural Sciences','Yes', 0,'N'),
('Chulu', 'Tukiya', '00-00-0000', 'Zambian', 'Female', 'Single', 'Ngombe compound', 'Central', 'email@mail.com', 13053536, 'Fourth', 'Biology', 'Five','GRZ 100%', 'Education','No', 0,'N'),

('Mumba', 'Prince', '00-00-0000', 'Zambian', 'Male', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 15053536, 'Fourth', 'Biology', 'Four','GRZ 75%', 'Natural Sciences','Yes', 0,'N'),
('Zulu', 'Harrison', '00-00-0000', 'Zambian', 'Male', 'Single', 'Ngombe compound', 'Luapula', 'email@mail.com', 14643743, 'Fourth', 'Biology', 'Five','GRZ 75%', 'Humanities','Yes', 0,'N'),
('Phiri', 'Peter', '00-00-0000', 'Zambian', 'Male', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 12083234, 'Fourth', 'Biology', 'Four','GRZ 100%', 'Natural Sciences','No', 0,'N'),
('Ndebi', 'John', '00-00-0000', 'Zambian', 'Male', 'Single', 'Ngombe compound', 'Luapula', 'email@mail.com', 12053434, 'Fourth', 'Biology', 'Four','GRZ 100%', 'Humanities','Yes', 0,'N'),
('Chileshe', 'Gift', '00-00-0000', 'Zambian', 'Male', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 16053545, 'Fourth', 'Biology', 'Five','GRZ 100%', 'Education','Yes', 0,'N'),
('Mbewe', 'Paul', '00-00-0000', 'Zambian', 'Male', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 12053512, 'Fourth', 'Biology', 'Four','GRZ 75%', 'Education','No', 0,'N'),
('Zulu', 'Francis', '00-00-0000', 'Zambian', 'Male', 'Single', 'Ngombe compound', 'Luapula', 'email@mail.com', 13053578, 'Fourth', 'Biology', 'Five','GRZ 100%', 'Humanities','No', 0,'N'),
('Mbuya', 'Papias', '00-00-0000', 'Zambian', 'Male', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 13053567, 'Fourth', 'Biology', 'Four','GRZ 100%', 'Natural Sciences','No', 0,'N'),
('Zulu', 'Samson', '00-00-0000', 'Zambian', 'Male', 'Single', 'Ngombe compound', 'Copperbelt', 'email@mail.com', 13053545, 'Fourth', 'Biology', 'Five','GRZ 75%', 'Education','No', 0,'N'),
('Fulwe', 'Shubert', '00-00-0000', 'Zambian', 'Male', 'Single', 'Ngombe compound', 'Luapula', 'email@mail.com', 13053509, 'Fourth', 'Biology', 'Four','GRZ 100%', 'Humanities','No', 0,'N'),
('Moba', 'Julius', '00-00-0000', 'Zambian', 'Male', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 13053590, 'Fourth', 'Biology', 'Four','GRZ 75%', 'Natural Sciences','No', 0,'N'),
('Mbeba', 'Chiso', '00-00-0000', 'Zambian', 'Male', 'Single', 'Ngombe compound', 'Copperbelt', 'email@mail.com', 11053578, 'Fourth', 'Biology', 'Five','GRZ 100%', 'Humanities','Yes', 0,'N'),
('Nkumba', 'David', '00-00-0000', 'Zambian', 'Male', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 11053556, 'Fourth', 'Biology', 'Four','GRZ 75%', 'Education','No', 0,'N'),
('Mwewa', 'Mathew', '00-00-0000', 'Zambian', 'Male', 'Single', 'Ngombe compound', 'Northern', 'email@mail.com', 11053512, 'Fourth', 'Biology', 'Five','GRZ 100%', 'Humanities','No', 0,'N'),
('Zulu', 'Silvester', '00-00-0000', 'Zambian', 'Male', 'Single', 'Ngombe compound', 'Copperbelt', 'email@mail.com', 11053523, 'Fourth', 'Biology', 'Four','GRZ 100%', 'Education','No', 0,'N'),
('Phiri', 'Gift', '00-00-0000', 'Zambian', 'Male', 'Single', 'Ngombe compound', 'Northern', 'email@mail.com', 11053345, 'Fourth', 'Biology', 'Four','GRZ 75%', 'Humanities','No', 0,'N'),
('Zulu', 'Ben', '00-00-0000', 'Zambian', 'Male', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 12054444, 'Fourth', 'Biology', 'Five','GRZ 75%', 'Natural Sciences','No', 0,'N'),
('Silanda', 'Edward', '00-00-0000', 'Zambian', 'Male', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 12053001, 'Fourth', 'Biology', 'Four','GRZ 100%', 'Education','No', 0,'N'),
('Chiseng', 'Sampa', '00-00-0000', 'Zambian', 'Male', 'Single', 'Ngombe compound', 'Northern', 'email@mail.com', 14053340, 'Fourth', 'Biology', 'Five','GRZ 100%', 'Natural Sciences','No', 0,'N'),



('Zulu', 'Sibongile', '00-00-0000', 'Non Zambian', 'Male', 'Married', 'Ngombe compound', 'Lusaka', 'email@mail.com', 15054556, 'Sixth', 'Biology', 'Six','GRZ 50%', 'Education','No', 0,'N'),
('Ndebi', 'Simeon', '00-00-0000', 'Non Zambian', 'Male', 'Married', 'Ngombe compound', 'Lusaka', 'email@mail.com', 15052344, 'Sixth', 'Biology', 'Six','GRZ 75%', 'Humanities','No', 0,'N'),
('Muwango', 'Orlando', '00-00-0000', 'Non Zambian', 'Male', 'Married', 'Ngombe compound', 'Lusaka', 'email@mail.com', 15051233, 'Sixth', 'Biology', 'Six','GRZ 50%', 'Education','No', 0,'N'),
('Fupa', 'Diya', '00-00-0000', 'Non Zambian', 'Male', 'Married', 'Ngombe compound', 'Lusaka', 'email@mail.com', 15053223, 'Sixth', 'Biology', 'Six','GRZ 75%', 'Education','Yes', 0,'N'),
('Mbedi', 'Moses', '00-00-0000', 'Non Zambian', 'Male', 'Married', 'Ngombe compound', 'Lusaka', 'email@mail.com', 15053455, 'Sixth', 'Biology', 'Six','GRZ 75%', 'Humanities','No', 0,'N'),
('Lungu', 'Peter', '00-00-0000', 'Non Zambian', 'Male', 'Married', 'Ngombe compound', 'Lusaka', 'email@mail.com', 15053676, 'Sixth', 'Biology', 'Six','Self Sponsor', 'Education','Yes', 0,'N'),
('Mfawali', 'Simon', '00-00-0000', 'Non Zambian', 'Male', 'Married', 'Ngombe compound', 'Lusaka', 'email@mail.com', 15053580, 'Sixth', 'Biology', 'Six','GRZ 75%', 'Education','No', 0,'N'),
('Zulu', 'Sibusiso', '00-00-0000', 'Non Zambian', 'Male', 'Married', 'Ngombe compound', 'Lusaka', 'email@mail.com', 15053530, 'Sixth', 'Biology', 'Six','GRZ 50%', 'Humanities','No', 0,'N'),

('Silanda', 'Sibo', '00-00-0000', 'Non Zambian', 'Female', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 16051223, 'Fourth', 'Biology', 'Seven','GRZ 50%', 'Humanities','No', 0,'N'),
('Buma', 'Diana', '00-00-0000', 'Non Zambian', 'Female', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 16055343, 'Fourth', 'Biology', 'Seven','GRZ 75%', 'Education','Yes', 0,'N'),
('Zulu', 'MaMercyry', '00-00-0000', 'Non Zambian', 'Female', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 16053533, 'Fourth', 'Biology', 'Seven','GRZ 75%', 'Humanities','No', 0,'N'),
('Newa', 'Mary', '00-00-0000', 'Non Zambian', 'Female', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 16052335, 'Fourth', 'Biology', 'Seven','GRZ 50%', 'Humanities','No', 0,'N'),
('Zulu', 'Mary', '00-00-0000', 'Non Zambian', 'Female', 'Single', 'Ngombe compound', 'Lusaka', 'email@mail.com', 16053565, 'Fourth', 'Biology', 'Seven','GRZ 50%', 'Education','No', 0,'N')
